const {app,BrowserWindow}=require('electron');const fs=require('fs');
app.disableHardwareAcceleration();app.whenReady().then(async()=>{const w=new BrowserWindow({show:false,width:1440,height:950,webPreferences:{nodeIntegration:true,contextIsolation:false,backgroundThrottling:false}});try{
await w.loadFile('index.html');const js=s=>w.webContents.executeJavaScript(s);const snap=async name=>{await w.webContents.capturePage();await new Promise(r=>setTimeout(r,400));fs.writeFileSync('qa/'+name+'.png',(await w.webContents.capturePage()).toPNG());};await w.webContents.insertCSS('*{transition:none!important;animation:none!important}');
await js("document.getElementById('play-button').click();document.getElementById('radar-button').click();world=new physics.Atmosphere({region:'gulf',temperature:29,dewpoint:27,sst:31,humidity:.95,lapse:7,cap:0,shear:2,contrast:0},isLand);selectedRadar=radarSites.find(s=>s.id==='KLCH');document.getElementById('radar-site-name').textContent='KLCH · Lake Charles';");
for(let i=0;i<8;i++){await js('advanceSimulation(360)');console.log(await js('JSON.stringify({hour:world.minutes/60,wind:world.tropicalWindKnots(),organization:world.tropical.organization})'));}
await js("radarProduct='reflectivity';refreshWorld();drawDomain();drawCities();focusRadar()");await new Promise(r=>setTimeout(r,250));await snap('evolved-hurricane');
await js("radarProduct='velocity';drawRadar()");await snap('evolved-hurricane-velocity');
await js("world=new physics.Atmosphere({region:'atlantic',temperature:2,dewpoint:0,contrast:20,forcing:1,shear:35,lapse:5.8,cap:2,humidity:.85,heating:100},isLand);selectedRadar=radarSites.find(s=>s.id===world.origin.site);document.getElementById('radar-site-name').textContent=selectedRadar.id;radarProduct='reflectivity';");await js('advanceSimulation(360)');await js('refreshWorld();drawDomain();drawCities();focusRadar()');await new Promise(r=>setTimeout(r,250));await snap('evolved-coastal-low');console.log(await js('JSON.stringify({pressure:world.low.pressure,summary:world.summary()})'));app.exit(0);
}catch(e){console.error(e);app.exit(1);}});
